clear
echo "                                               HOŞ GELDİNİZ"
sleep 1
echo "					           _,.-------.,_ "
echo "					       ,;~'             '~;, "
echo "					     ,;                     ;, "
echo "					    ;                         ; "
echo "					   ,'                         ', "
echo "					  ,;                           ;, "
echo "					  ; ;      .           .      ; ; "
echo "					  | ;   ______       ______   ; | "
echo "					  |  '/~'     ~' . '~     '~\'  | "
echo "					  |  ~  ,-~~~^~, | ,~^~~~-,  ~  | "
echo "					   |   |        }:{        |   | "
echo "					   |   l       / | \       !   | "
echo "					   .~  (__,.--' .^. '--.,__)  ~. "
echo "					   |     ---;' / | \ ';---     | "
echo "					    \__.       \/^\/       .__/ "
echo "					     V| \                 / |V "
echo "					      | |T~\___!___!___/~T| | "
echo "					      | |'IIII_I_I_I_IIII'| | "
echo "					      |  \,III I I I III,/  | "
echo "					       \   '~~~~~~~~~~'    / "
echo "				         	\   .         .   / "
echo "				          	 \_______^_______/ "
echo ""

